
# CL General
start_task: 0
total_tasks: 2

# CL Strategy
pseudo_label: True
distill_attn: True
teacher_path: "/kaggle/input/checkpoint-for-mtsd-model/15071_t1_5e_ap20.0.pth"

# CL Rehearsal
rehearsal: True

# CL Eval
fpp: True

# WandB
wandb_name: "7010_t0_10e"
